In [1]:
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt

In [27]:
#风速 v_wind_speed Weibull分布
v_wind_speed_Weibull_distribution=stats.weibull_min.rvs(2, 10, size=100)

In [28]:
v_wind_speed_Weibull_distribution

array([10.26322301, 11.36314139, 11.13173006, 10.35250222, 10.34145864,
       11.54939953, 10.50925845, 10.94134927, 11.09897557, 10.67151003,
       10.97659666, 10.63082465, 11.54959721, 11.67300664, 11.43840068,
       11.0122113 , 10.5944657 , 11.2223758 , 10.19250249, 10.31719346,
       10.61461235, 10.53914026, 11.16837692, 11.33710566, 11.2807491 ,
       11.16531446, 10.96784348, 10.33528069, 10.57594212, 10.59408789,
       11.14469733, 10.40903269, 11.65399262, 10.92954492, 11.13955522,
       10.70111667, 10.15722623, 11.04749174, 10.15957952, 11.27919345,
       11.04589888, 10.6810637 , 10.37876634, 10.76142991, 10.51123405,
       11.01534187, 10.93642831, 10.37427117, 11.01943829, 10.41310501,
       11.14759876, 10.67305449, 10.94056717, 10.51274944, 11.52916587,
       10.52211982, 11.59732906, 10.79997055, 10.77784277, 10.71286228,
       10.64220465, 11.0165434 , 10.71456513, 10.85278814, 10.98267687,
       10.8204732 , 11.81180035, 11.07837636, 10.38911167, 11.05

In [1]:
import numpy as np
import random

In [2]:
#需求侧用电需求d_power_demand 均匀分布
d_power_demand_uniform_distribution=np.random.uniform(70,80,[1,1000])

In [3]:
d_power_demand_uniform_distribution

array([[74.91539524, 73.34483678, 79.28655605, 77.83452438, 71.90572467,
        75.17033455, 71.96969819, 71.46915874, 70.65240144, 75.76842364,
        74.05372073, 77.33511631, 71.60437161, 79.30819321, 72.80217073,
        74.72768947, 79.35708536, 70.66533714, 76.94183347, 78.87124462,
        77.65028789, 72.62697001, 71.78429346, 73.23455676, 74.51473794,
        70.97550214, 71.61349392, 70.98016961, 74.00740723, 74.3252373 ,
        79.21591111, 78.78345602, 72.55616317, 74.19096731, 76.58478664,
        78.2244124 , 76.5587005 , 74.96894512, 71.33085694, 76.02190884,
        75.45346484, 78.39762505, 73.09056618, 73.08997454, 71.64365468,
        72.69055795, 75.27556722, 70.77055403, 75.77469866, 73.97618771,
        72.79054898, 71.69895783, 73.28318446, 77.45125733, 77.73409257,
        77.56026457, 77.08172713, 76.18650946, 74.91184014, 71.71895799,
        73.50426112, 72.66945993, 71.60543173, 71.72295497, 77.40589128,
        76.63714329, 77.68715264, 73.85473232, 74.2

In [4]:
np.savetxt('./data/d_power_demand_uniform_distribution_[70,80].txt',d_power_demand_uniform_distribution,fmt='%0.8f')

In [1]:
import numpy as np
import random

In [2]:
#需求侧用电需求d_power_demand 高斯分布/正态分布
mu1 = 50  #期望为2
sigma1 = 5  #标准差为0.5
num1 = 1000  #个数为100
d_power_demand_uniform_distribution=np.random.normal(mu1, sigma1, num1)

In [3]:
d_power_demand_uniform_distribution

array([52.39917442, 48.69971978, 43.13610371, 56.34429211, 49.93984711,
       57.29857888, 50.01425758, 42.09134791, 51.54850859, 44.75747594,
       50.70057141, 57.78720016, 52.45401943, 46.33736975, 47.7402553 ,
       42.42989763, 55.3431228 , 60.47604267, 46.63200257, 60.35956177,
       50.93549965, 54.24621244, 43.29136828, 51.92361446, 40.65257444,
       50.92135574, 46.39943532, 47.34563077, 45.47788111, 52.979071  ,
       54.45410322, 51.02267546, 55.31661444, 49.61629042, 50.61021098,
       52.89667243, 51.22567814, 55.86517443, 43.63663834, 58.70780972,
       54.75226644, 57.9621305 , 46.2456984 , 52.31889507, 44.5457683 ,
       53.67589536, 48.58008391, 44.13381921, 48.91507647, 46.82343774,
       45.88929246, 49.89098841, 50.48673918, 53.68115828, 39.98508362,
       45.57395432, 49.8977976 , 56.89808741, 52.94717344, 55.97012519,
       43.81696377, 44.04283224, 57.27570948, 55.27445039, 44.46210475,
       48.02563881, 45.35628231, 55.12053509, 47.16039699, 51.19

In [4]:
np.savetxt('./data/d_power_demand_normal_distribution_(50,5).txt',d_power_demand_uniform_distribution,fmt='%0.8f')

In [ ]:
#风速分布参数c 均匀分布[3,25]

In [1]:
import numpy as np
import random

In [2]:
c_wind_speed_uniform_distribution=np.random.uniform(3,25,[1,1000])

In [3]:
c_wind_speed_uniform_distribution

array([[ 8.301041  , 14.69554708, 11.73462138, 20.88797006, 17.01236112,
        11.53887689, 20.17759   , 12.95856003,  4.42860238, 13.39240335,
         3.71616054, 22.04759493, 22.07798354, 24.23535384, 14.77327144,
        22.01070443, 24.26368821, 17.54487156,  4.81637973, 22.76341842,
         7.10546984, 20.89161523,  4.73395435, 18.17359002,  4.48706041,
        11.55331759, 11.11125981, 13.22114577, 16.55283022,  7.5123474 ,
         6.9741147 , 23.88060792, 15.04406637, 19.92973653, 18.72716024,
         6.39076728, 13.13882751, 11.1220032 , 13.24723589, 16.1306981 ,
         6.82066779, 20.56266068, 16.78809727,  4.64855439, 10.46389601,
        20.47634713, 17.32693181,  3.86330913,  7.40752313, 22.00829826,
         5.26250906, 15.14406894,  5.12234174, 12.16619144, 22.36919315,
        11.99698907, 15.44183264, 16.83610515, 22.89098311,  3.67942984,
        21.67796548, 17.84025909, 23.39542542,  9.44486706, 21.27732194,
        15.88798893, 17.69128058, 23.16904116, 21.7

In [4]:
np.savetxt('./data/c_wind_speed_uniform_distribution_(3,25).txt',c_wind_speed_uniform_distribution,fmt='%0.8f')

In [5]:
#风速分布参数kappa 均匀分布[1,2]

In [5]:
import numpy as np
import random

In [6]:
kappa_wind_speed_uniform_distribution=np.random.uniform(2,3,[1,1000])

In [7]:
kappa_wind_speed_uniform_distribution

array([[2.66836324, 2.10218816, 2.30593756, 2.49450248, 2.63537814,
        2.44466253, 2.96946266, 2.36446438, 2.42410411, 2.3728007 ,
        2.52674506, 2.67853757, 2.67292298, 2.6829301 , 2.06624199,
        2.82899266, 2.29481562, 2.9754401 , 2.19682287, 2.30087244,
        2.49300975, 2.7421258 , 2.61322499, 2.07787691, 2.43670989,
        2.5075835 , 2.9635753 , 2.23501543, 2.00468584, 2.84390111,
        2.01470627, 2.21015256, 2.84368377, 2.02497384, 2.20984039,
        2.33880209, 2.50711526, 2.6107788 , 2.82993949, 2.8517004 ,
        2.77092585, 2.58185793, 2.97407755, 2.35217994, 2.65936912,
        2.50325377, 2.2671669 , 2.21216588, 2.00645313, 2.94725191,
        2.33337829, 2.70649909, 2.62349488, 2.37153232, 2.70555592,
        2.40102409, 2.70577593, 2.90856758, 2.70343229, 2.8289405 ,
        2.50683097, 2.57965073, 2.57062343, 2.57336885, 2.67717087,
        2.87924786, 2.57062645, 2.63797045, 2.36734285, 2.84603622,
        2.27330299, 2.00021162, 2.81573866, 2.74

In [8]:
np.savetxt('./data/kappa_wind_speed_uniform_distribution_(2,3).txt',kappa_wind_speed_uniform_distribution,fmt='%0.8f')

In [1]:
import numpy as np
import random

In [2]:
start = 30
end = 120
increment = (end - start) / 1000

numbers = [start + i * increment for i in range(1000)]

print(numbers)

[30.0, 30.09, 30.18, 30.27, 30.36, 30.45, 30.54, 30.63, 30.72, 30.81, 30.9, 30.99, 31.08, 31.17, 31.26, 31.35, 31.44, 31.53, 31.62, 31.71, 31.8, 31.89, 31.98, 32.07, 32.16, 32.25, 32.34, 32.43, 32.52, 32.61, 32.7, 32.79, 32.88, 32.97, 33.06, 33.15, 33.24, 33.33, 33.42, 33.51, 33.6, 33.69, 33.78, 33.87, 33.96, 34.05, 34.14, 34.23, 34.32, 34.41, 34.5, 34.59, 34.68, 34.769999999999996, 34.86, 34.95, 35.04, 35.13, 35.22, 35.31, 35.4, 35.49, 35.58, 35.67, 35.76, 35.85, 35.94, 36.03, 36.12, 36.21, 36.3, 36.39, 36.48, 36.57, 36.66, 36.75, 36.84, 36.93, 37.019999999999996, 37.11, 37.2, 37.29, 37.38, 37.47, 37.56, 37.65, 37.74, 37.83, 37.92, 38.01, 38.1, 38.19, 38.28, 38.37, 38.46, 38.55, 38.64, 38.730000000000004, 38.82, 38.91, 39.0, 39.09, 39.18, 39.269999999999996, 39.36, 39.45, 39.54, 39.629999999999995, 39.72, 39.81, 39.9, 39.99, 40.08, 40.17, 40.26, 40.35, 40.44, 40.53, 40.62, 40.71, 40.8, 40.89, 40.980000000000004, 41.07, 41.16, 41.25, 41.34, 41.43, 41.519999999999996, 41.61, 41.7, 41.79

In [3]:
np.savetxt('./data/d_power_demand_increasing_[30,120].txt',numbers,fmt='%0.8f')

In [ ]:
#生成攻击值

In [ ]:
#小值高斯攻击 均值为-150 

In [8]:
import numpy as np
import random

In [9]:
mu1 = -150  #期望
sigma1 = 5  #标准差
num1 = 1000  #个数为1000
small_Gaussian_Byzantine_attack=np.random.normal(mu1, sigma1, num1)

In [10]:
small_Gaussian_Byzantine_attack

array([-149.59297205, -152.33055808, -147.51183453, -145.00710886,
       -145.87573238, -154.42625175, -163.43373442, -141.96457608,
       -154.16160058, -149.55364001, -148.14055115, -150.06782297,
       -152.45496394, -145.35215795, -142.48595467, -152.22409676,
       -153.10996034, -152.39496363, -146.20768333, -156.03635955,
       -151.5368314 , -148.17079075, -144.37409471, -150.66753933,
       -141.18660551, -145.53643026, -155.52368054, -157.87069272,
       -153.67889617, -149.31267642, -148.41456199, -142.53154216,
       -151.60440327, -147.23689824, -148.22634366, -150.49425491,
       -145.88992903, -154.24329388, -146.26604819, -148.26194036,
       -149.04548139, -145.99577022, -152.39055156, -152.79796576,
       -149.07272545, -145.69625775, -147.62537465, -153.76863862,
       -155.44119583, -153.80884463, -143.16058607, -143.16310446,
       -144.17742657, -151.38419596, -152.95910987, -155.41167026,
       -157.93119141, -147.65523001, -135.09639988, -152.67076

In [11]:
np.savetxt('./data/small_Gaussian_Byzantine_attack_(-150,5).txt',small_Gaussian_Byzantine_attack,fmt='%0.8f')

In [ ]:
#大值高斯攻击 均值为-10 

In [1]:
import numpy as np
import random

In [2]:
mu2 = -10  #期望
sigma2 = 5  #标准差
num2 = 1000  #个数为1000
large_Gaussian_Byzantine_attack=np.random.normal(mu2, sigma2, num2)

In [5]:
large_Gaussian_Byzantine_attack

array([ -4.09660692,  -9.23941845, -14.20669738,  -9.20396922,
       -18.0954435 ,  -5.96549267, -11.65296038, -16.2645874 ,
       -17.09768272, -13.01555695,  -8.6044179 , -15.88658941,
       -10.94763918,  -8.4579762 ,  -8.80487891,  -5.72045939,
       -18.93383069,  -9.79297611,  -7.0281088 ,  -7.41537487,
        -8.75477426,  -7.21969714,  -8.54206195,  -8.18893607,
       -11.28797568,  -8.97148206,  -8.72039781, -10.43346352,
       -16.57515529, -11.53092105, -16.89157044,  -8.73524371,
        -8.47049405, -13.07606569,  -9.99840594, -11.09397655,
       -12.70074705,  -9.02665971,  -5.39951202,  -6.16777251,
        -5.31472133,   0.        ,  -3.53134291,  -6.19514008,
        -0.83826953, -11.4400194 ,  -8.94630051, -10.01412096,
        -1.167592  ,  -4.60734903, -10.27508309,  -8.23193019,
        -4.34130079, -20.02863984, -13.0692722 ,  -9.38001065,
        -7.30521013,  -9.72538596, -14.39901999, -12.76120502,
        -3.51556421, -23.22349427,  -9.62537742, -15.18

In [4]:
for i in range(0,1000):
    if large_Gaussian_Byzantine_attack[i]>0:
        print(large_Gaussian_Byzantine_attack[i])
        large_Gaussian_Byzantine_attack[i]=0

2.7100035530356834
0.07919705052118786
3.616523320574405
0.5081372805763262
0.49328522646443496
0.90202925217746
0.8848325297289978
0.3634691651201649
1.071703651635925
1.561073034482476
1.9223009446161292
0.32116400053126704
0.4081010370107663
6.568782153262582
1.2968979609592868
1.9856387928784276
4.084564857015751
0.81651771573795
8.92288123665352


In [6]:
np.savetxt('./data/large_Gaussian_Byzantine_attack_(-10,5).txt',large_Gaussian_Byzantine_attack,fmt='%0.8f')